FROM ghcr.io/nerfstudio-project/nerfstudio:latest

# Set work directory
WORKDIR /workspace/project

# Copy project files
COPY . .

# Default shell
CMD ["/bin/bash"]
1~FROM ghcr.io/nerfstudio-project/nerfstudio:latest

# Set work directory
WORKDIR /workspace/project

# Copy project files
COPY . .

# Default shell
CMD ["/bin/bash"]
